# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 12:24
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=10)),
                ('code', models.IntegerField()),
                ('fclass', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('geom_multipolygon', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255, unique=True)),
                ('update_link', models.CharField(max_length=255)),
                ('download_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Landuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=10)),
                ('code', models.IntegerField()),
                ('fclass', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('geom_multipolygon', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Natural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=10)),
                ('code', models.IntegerField()),
                ('fclass', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('geom_multipoint', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=10)),
                ('code', models.IntegerField()),
                ('fclass', models.CharField(max_length=20)),
                ('population', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('geom_multipoint', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Pofw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=10)),
                ('code', models.IntegerField()),
                ('fclass', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('geom_multipoint', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Pois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=10)),
                ('code', models.IntegerField()),
                ('fclass', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('geom_multipoint', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Railways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=10)),
                ('code', models.IntegerField()),
                ('fclass', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('geom_multilinestring', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=10)),
                ('code', models.IntegerField()),
                ('fclass', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=20)),
                ('oneway', models.CharField(max_length=1)),
                ('maxspeed', models.IntegerField()),
                ('layer', models.FloatField()),
                ('bridge', models.CharField(max_length=1)),
                ('tunnel', models.CharField(max_length=1)),
                ('geom_multilinestring', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Shapefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('driver', models.CharField(max_length=255)),
                ('csr', models.CharField(max_length=255)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField()),
                ('geom', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=10)),
                ('code', models.IntegerField()),
                ('fclass', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('geom_multipoint', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Country')),
                ('shapefile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Shapefile')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=10)),
                ('code', models.IntegerField()),
                ('fclass', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('geom_multipoint', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Country')),
                ('shapefile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Shapefile')),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=10)),
                ('code', models.IntegerField()),
                ('fclass', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('geom_multipolygon', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Country')),
                ('shapefile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Shapefile')),
            ],
        ),
        migrations.CreateModel(
            name='Waterways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=10)),
                ('code', models.IntegerField()),
                ('fclass', models.CharField(max_length=20)),
                ('width', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('geom_multilinestring', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Country')),
                ('shapefile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Shapefile')),
            ],
        ),
        migrations.AddField(
            model_name='roads',
            name='shapefile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Shapefile'),
        ),
        migrations.AddField(
            model_name='railways',
            name='shapefile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Shapefile'),
        ),
        migrations.AddField(
            model_name='pois',
            name='shapefile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Shapefile'),
        ),
        migrations.AddField(
            model_name='pofw',
            name='shapefile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Shapefile'),
        ),
        migrations.AddField(
            model_name='places',
            name='shapefile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Shapefile'),
        ),
        migrations.AddField(
            model_name='natural',
            name='shapefile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Shapefile'),
        ),
        migrations.AddField(
            model_name='landuse',
            name='shapefile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Shapefile'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Country'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='shapefile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hikerdb.Shapefile'),
        ),
    ]
